name:       apk-build
version:    0.0.1
synopsis:   Utilities to build APK packages
homepage:   https://github.com/mbj/apk-build
author:     Markus Schirp
maintainer: mbj@schirp-dso.com
copyright:  2020 Markus Schirp
github:     mbj/apk-build

dependencies:
- amazonka                == 1.6.1
- amazonka-cloudformation == 1.6.1
- amazonka-core           == 1.6.1
- amazonka-s3             == 1.6.1
- base                    ^>= 4.13 || ^>= 4.14
- bounded                 ^>= 0.0.1
- bytestring              ^>= 0.10
- containers              ^>= 0.6
- conversions             ^>= 0.0.1
- exceptions              ^>= 0.10
- filepath                ^>= 1.4
- hashable                ^>= 1.3
- lens                    ^>= 4.18 || ^>= 4.19
- mprelude                ^>= 0.2.1
- mrio-amazonka           ^>= 0.0.1
- mrio-core               ^>= 0.0.1
- mrio-log                ^>= 0.0.1
- optparse-applicative    ^>= 0.15 || ^>= 0.16
- pathtype                ^>= 0.8
- resourcet               ^>= 1.2
- source-constraints      ^>= 0.0.2
- stack-deploy            ^>= 0.0.1
- stratosphere            ^>= 0.58 || ^>= 0.59
- template-haskell        ^>= 2.15 || ^>= 2.16
- text                    ^>= 1.2
- text-conversions        ^>= 0.3
- th-lift-instances       ^>= 0.1
- typed-process           ^>= 0.2.6
- unliftio-core           ^>= 0.2

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fplugin=SourceConstraints
- -funbox-strict-fields

default-extensions:
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- NumericUnderscores
- OverloadedLists
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- Strict
- TemplateHaskell
- TypeApplications
- TypeFamilies

executables:
  apk-build:
    main: app/CLI.hs
    ghc-options: &ghc-options
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies: apk-build

library:
  source-dirs:
  - src
  exposed-modules:
  - APK.CLI
  - APK.StackDeploy

tests:
  test:
    main: Test.hs
    source-dirs: test
    ghc-options: *ghc-options
    dependencies:
    - apk-build
    - devtools
    - tasty
    - tasty-mgolden
